version: '3'
services:
  elasticsearch:
    image: elasticsearch:1.5
    # ports:
    #   - "9200:9200"
    #   - "9300:9300"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        RACK_ENV: development
        REVISION: 559c-fake-revision-string-f9fb
    ports:
      - "3000:3000"
    volumes:
        - ./:/zoo_stats
    environment:
      PORT: 3000
      ES_TRANSPORT_LOGGING: 'true'
      RACK_ENV: development
      ZOO_STATS_ENV: development
      PUMA_MAX_THREADS: 1
      CORS_ORIGINS: '(127\.0\.0\.1|localhost|[a-z0-9-]+\.zooniverse\.org)'
    links:
      - elasticsearch

  stream:
    build:
      context: .
      dockerfile: Dockerfile.stream
      args:
        RACK_ENV: development
    volumes:
        - ./:/zoo_stats
    environment:
      ES_TRANSPORT_LOGGING: 'true'
      RACK_ENV: development
      ZOO_STATS_ENV: development
    links:
      - elasticsearch
