elasticsearch:
  image: elasticsearch:1.5.2
  # ports:
  #   - "9200:9200"
  #   - "9300:9300"

zoostats:
  dockerfile: Dockerfile.dev
  build: .
  ports:
    - "3000:3000"
  volumes:
      - ./:/zoo_stats
  environment:
    RACK_ENV: development
    ZOO_STATS_ENV: development
    CORS_ORIGINS: '(127\.0\.0\.1|localhost|[a-z0-9-]+\.zooniverse\.org)'
  links:
    - elasticsearch
