elasticsearch:
  image: elasticsearch:1.5.2
  # ports:
  #   - "9200:9200"
  #   - "9300:9300"

timescale:
  image: timescale/timescaledb-postgis:1.0.0-pg10
  environment:
    - "POSTGRES_USER=zoo_stats"
    - "POSTGRES_PASSWORD=zoo_stats"
  ports:
    - "5432"

zoostats:
  dockerfile: Dockerfile.dev
  build: .
  ports:
    - "3000:3000"
  environment:
    RACK_ENV: development
    ZOO_STATS_ENV: development
    CORS_ORIGINS: '(127\.0\.0\.1|localhost|[a-z0-9-]+\.zooniverse\.org)'
  volumes:
    - $HOME/.aws/:/root/.aws
  links:
    - elasticsearch
    - timescale
