FROM zooniverse/ruby:2.2.1

MAINTAINER Campbell Allen

# Apt-get install dependencies
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install --no-install-recommends -y git && \
    apt-get clean

WORKDIR /zoo_stats

ADD ./Gemfile /zoo_stats/
ADD ./Gemfile.lock /zoo_stats/

RUN bundle install

ADD ./ /zoo_stats

ENTRYPOINT /zoo_stats/bin/start.sh
