elasticsearch:
  image: elasticsearch:1.7.3
  # ports:
  #   - "9200:9200"
  #   - "9300:9300"

zookeeper:
  image: zooniverse/zookeeper
  command: /usr/share/zookeeper/bin/zkServer.sh start-foreground -c localhost:2888:3888 -i 1

kafka:
  image: zooniverse/kafka
  hostname: kafka
  command: -i 1 -H kafka -p 9092 -z zk:2181
  links:
    - zookeeper:zk

zoostats:
  dockerfile: Dockerfile.dev
  build: .
  ports:
    - "3000:3000"
  environment:
    RACK_ENV: development
    ZOO_STATS_ENV: development
  links:
    - zookeeper:zk
    - kafka
    - elasticsearch
