FROM ruby:2.6

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install --no-install-recommends -y git supervisor && \
    apt-get clean

WORKDIR /zoo_stats

ARG REVISION=''
ENV REVISION=$REVISION

ADD ./Gemfile /zoo_stats/
ADD ./Gemfile.lock /zoo_stats/

RUN bundle install --without development test

EXPOSE 80

ADD ./ /zoo_stats

ADD supervisord.api.conf /etc/supervisor/conf.d/zoo_event_stats_api.conf

ENTRYPOINT /zoo_stats/bin/start.sh
