FROM ruby:2.3

MAINTAINER Campbell Allen

# Apt-get install dependencies
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install --no-install-recommends -y git supervisor default-jre-headless && \
    apt-get clean

ENV JAVA_HOME /usr/bin/java

WORKDIR /zoo_stats

ADD ./Gemfile /zoo_stats/
ADD ./Gemfile.lock /zoo_stats/

RUN bundle install

ADD ./Rakefile /zoo_stats/
RUN rake download_jars

ADD ./ /zoo_stats

ENTRYPOINT /zoo_stats/bin/start.sh
